### ISSUE TITLE
Consider allowed relayers wildcard case

### ISSUE THREAD

**Issue by minghinmatthewlam** [ava-labs/teleporter#10]
**Context and scope**
Currently Teleporter messages allow any relayers when the `allowedRelayers` array is empty, we could possibly look at having a special address value such as `0x00...00`.

**Comment by michaelkaplan13** [comment]
Given that this issue was not mentioned in any of the audits, lets plan on moving forward with it as is.

That is, an empty `allowedRelayers` array denotes the case where anyone can relay the message.
