### ISSUE TITLE
Update docs to be compatible with the documentation site

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/teleporter#144]
**Context and scope**
The docs website (https://docs.avax.network/) converts markdown into a beautified website. In order to do this, we need to make the following changes to https://github.com/ava-labs/teleporter/blob/main/contracts/src/Teleporter/README.md and https://github.com/ava-labs/teleporter/tree/main/contracts/src/CrossChainApplications#getting-started-with-an-example-application
- Put all documentation intended for the site in standalone markdown files (for example, separate the Getting Started section into its own file)
- Convert all relative paths in links to absolute paths
- Close all html tags

**Comment by michaelkaplan13** [comment]
Closing as completed thanks to the ongoing DevRel effort to keep the docs up to date 🙏
