### ISSUE TITLE
Investigate nil tx in E2E test

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/teleporter#151]
In the test `RetrySuccessfulExecution`, the call to `RetryMessageExecution` after the message has already been successfully executed is expected to fail. It fails, however, with a `nil` transaction that is never mined, which is unexpected. We should investigate the cause.

_Originally posted by @minghinmatthewlam in https://github.com/ava-labs/teleporter/pull/93#discussion_r1396483429_

**Comment by geoff-vball** [comment]
The transaction is in fact mined, but the go bindings do not return the tx if the call errors.

`BoundContract.transact()` in `subnet-evm/accounts/abi/bind/base.go`, which all the abi-generated go bindings call when calling any of their functions, always returns a `nil` tx if there is an error. 

If we really want to check the tx, we can set `opts.NoSend` in the `transactor` object and call the function again, which will return the `tx`. Or we can file a ticket with `subnet-evm` if we think this is incorrect behaviour.
