### ISSUE TITLE
Add to CLI unit tests

### ISSUE THREAD

**Issue by minghinmatthewlam** [ava-labs/teleporter#174]
**Context and scope**
There are some basic unit tests in [PR](https://github.com/ava-labs/teleporter/pull/137), but we can also add unit tests with basic inputs. There are unit tests on branch `cli-unit-tests`, which run successfully individually, but ran altogether in `go test ./...` they fail. This is likely due to some shared state, and the commands not reinitializing between the test cases.

**Discussion and alternatives**
In the unit tests might need to make copies of the commands to initialize between test cases.

**Comment by michaelkaplan13** [comment]
Closing this since the Teleporter CLI is going to be removed in favor of commands within the Avalanche CLI as a part of https://github.com/ava-labs/teleporter/issues/377
