### ISSUE TITLE
Author C-Chain <> subnet integration tests

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/teleporter#193]
**Context and scope**
As of Avalanchego 1.10.17, Warp is activated by default on local networks. There is therefore no special setup required to author integration tests that send Teleporter messages between the C-Chain and subnets.

**Discussion and alternatives**
The test cases we should include are:
- Send basic Teleporter messages between the C-Chain and a subnet
- Replicate/rewrite the native token bridge test cases to source assets from the C-Chain
- Validator churn with the C-Chain as the source chain

**Comment by geoff-vball** [comment]
Would it make sense instead of duplicating tests, to modify the testing interface to provide a couple different choices for `localNetworkInstance`, which a variation that has the c-chain as subnetA or subnetB, then we could pass that instance into the already existing tests.
