### ISSUE TITLE
[Bug]: Some runs of `run.sh` fail on ARM64

### ISSUE THREAD

**Issue by geoff-vball** [ava-labs/teleporter#278]
[logs.txt](https://github.com/ava-labs/teleporter/files/14195540/logs.txt)

**Describe the bug**
`./scripts/local/run.sh` fails intermittently when running on ARM64. This may be an issue with one of our dependencies.

**To Reproduce**
Run `./scripts/local/run.sh`. `run_setup.sh` will sometimes fail when calling one of the instances of `avalanche subnet deploy`.

**Expected behavior**
The script should run normally without exiting.

**Logs**
Attached

**Operating System**
Mac ARM64

**Comment by geoff-vball** [comment]
After some investigation, it seems that `run.sh` does not succeed on every clean run, and the failures seem to be fairly random. I've updated the bug description to reflect this.

**Comment by cam-schultz** [comment]
It sounds like this is an `avalanche-cli` bug. Do you mind opening an issue in that repo and closing this one out?

**Comment by geoff-vball** [comment]
@cam-schultz I'm actually getting `Error: no RPC version found` now on both systems when trying to import genesis. I'm pretty sure this is because `avalanche-cli` hasn't been updated to be compatible with `subnet-evm` `v0.6.0-fuji`. I'll wait until they update for Durango compatibility, and then reassess if this is still an issue.

**Comment by michaelkaplan13** [comment]
Closing this issue out since the local setup scripts are being removed in https://github.com/ava-labs/teleporter/pull/393/files in favor of the Avalanche CLI support
