### ISSUE TITLE
Require Go >= 1.21.7

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/teleporter#279]
**Context and scope**
Go v1.21.7 was released on 2-6-2024. The changelist can be found [here](https://github.com/golang/go/issues?q=milestone%3AGo1.21.7+label%3ACherryPickApproved). The 1.21 release notes can be found [here](https://tip.golang.org/doc/go1.21).

We should replace any experimental packages with new packages included in Go 1.21 where applicable.

**Comment by geoff-vball** [comment]
Completed via https://github.com/ava-labs/teleporter/pull/280
