### ISSUE TITLE
[Bug]: Running the local network setup looks like it hangs when it runs cast publish

### ISSUE THREAD

**Issue by sharife3** [ava-labs/teleporter#331]
**Describe the bug**
After having to add a configuration to allow for unprotected tx due to EIP-155 spec, and proceed, it appears this now hangs at publish. If this is not set then it complains that only replay-protected tx can be sent in, which would require a modification of the tx create in go to include the chainId that you are submitting tx too.

**To Reproduce**
1. Using the following config for genesis: 
`{
  "config": {
    "chainId": "<EVM_CHAIN_ID>",
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "muirGlacierBlock": 0,
    "subnetEVMTimestamp": 0,
    "dUpgradeTimestamp": 0,
    "durangoTimestamp": 0,
    "feeConfig": {
      "gasLimit": 20000000,
      "minBaseFee": 1000000000,
      "targetGas": 100000000,
      "baseFeeChangeDenominator": 48,
      "minBlockGasCost": 0,
      "maxBlockGasCost": 10000000,
      "targetBlockRate": 2,
      "blockGasCostStep": 500000
    },
    "warpConfig": {
      "blockTimestamp": 0,
      "quorumNumerator": 67
    }
  },
  "alloc": {
    "8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC": {
      "balance": "0x52B7D2DCC80CD2E4000000"
    }
  },
  "nonce": "0x0",
  "timestamp": "0x0",
  "extraData": "0x00",
  "gasLimit": "0x1312D00",
  "difficulty": "0x0",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
`
and the following config for node config:

`{
  "log-level": "info",
  "warpConfig": {
    "blockTimestamp": 0
  },
  "allow-unprotected-txs": true
}
`
Running the following command: 
`./scripts/local/run.sh`

it appears only the following log line comes out: 
`relayer_run        | Waiting for subnets to start up. Retry count: 298`

Then eventually exits

**Expected behavior**
Local network runs up and executes the test transfers between subnets to see how teleporter works

**Logs**
Last log for local_network_run
`local_network_run  | Sent ether to teleporter deployer on each subnet.`

Last log for relayer_run        
`relayer_run        | Waiting for subnets to start up. Retry count: 298`

**Operating System**
WSL - Windows

**To best protect the Avalanche community security bugs should be reported in accordance to our [Security Policy](../../SECURITY.md)**

**Comment by cam-schultz** [comment]
Hey @sharife3. We've only tested this Docker setup on Linux and Mac platforms, so we can't say for certain what changes would need to be made to get this running on Windows.

As an alternative development environment, I'd suggest https://github.com/ava-labs/teleporter-starter-kit, which provides a containerized setup that can be run locally as well as in a remote codespace. It runs everything in a single container, which may bypass the networking issues you are hitting. If your not able to get that working locally, I'd recommend running it in a codespace per the README instructions.

**Comment by cam-schultz** [comment]
Closing this issue out since we're not planning on directly supporting Windows for this Docker setup.
