### ISSUE TITLE
[Bug]: deploy registry fails on subnet-evm

### ISSUE THREAD

**Issue by lumos42** [ava-labs/teleporter#362]
**Describe the bug**
TeleporterRegistry deployment on subnet-evm fails

**To Reproduce**
```
1. Spin up a subnet-evm local network

2. ./scripts/deploy_teleporter.sh --version v1.0.0 --rpc-url "http://127.0.0.1:9650/ext/bc/<blocjchain_id>/rpc" --private-key <private_key>
# works

3. ./scripts/deploy_registry.sh --version v1.0.0 --rpc-url "http://127.0.0.1:9650/ext/bc/<blocjchain_id>/rpc" --private-key <private_key>
# fails with error = "server returned an error response: error code -32000: execution reverted"
```

**Expected behavior**
The script should succeed

**Logs from the script execution**
```
Error:
server returned an error response: error code -32000: execution reverted
```

**Logs from subnet-evm**
```
t=2024-04-14T16:58:42.652095+0530 lvl=info msg="Caller gas above allowance, capping"    requested=500000000 cap=50000000 type=system caller=api.go:1274
t=2024-04-14T16:58:42.653456+0530 lvl=eror msg="Served eth_estimateGas"                 reqid=3 execTime=1.522584ms  procTime=1.52325ms   totalTime=1.523333ms  err="execution reverted" type=system caller=handler.go:526
```

**Operating System**
MacOS 14.0 (23A344) with Apple silicon

**Comment by geoff-vball** [comment]
Hey @shubhamgoyal42, could you help us out with a little more info?

- `subnet-evm` version
- `teleporter` version
- Genesis file for your network.

**Comment by shubhamgoyal42** [comment]
Hi @geoff-vball,
- `subnet-evm` v0.6.2
- `teleporter` v1.0.0
- [genesis file](https://github.com/hubble-exchange/hubblenet/blob/teleporter/genesis.json)

**Comment by geoff-vball** [comment]
@shubhamgoyal42 I ran a network with the same genesis file, but added 
`
    "warpConfig": {
      "blockTimestamp": 0
    }`
and I was able to deploy the contract as expected.

Can you please confirm that the Warp precompile is correctly enabled on your Subnet? You can check this by calling [getActivePrecompilesAt](https://docs.avax.network/reference/subnet-evm/api#eth_getactiveprecompilesat) via RPC.

**Comment by michaelkaplan13** [comment]
Hey @lumos42 are you still hitting this issue?

**Comment by michaelkaplan13** [comment]
Closing this issue because it looks stale, but feel free to re-open if you're still having the same problem.
