### ISSUE TITLE
Consider emitting TeleporterMessage hash in events

### ISSUE THREAD

**Issue by minghinmatthewlam** [ava-labs/teleporter#4]
**Context and scope**
We currently emit the full (unbounded size) TeleporterMessage in certain event logs in TeleporterMessenger.sol. We should consider emitting the hash of the TeleporterMessage instead to save on gas. We would need to consider if that would affect indexers at all.

**Discussion and alternatives**
One idea is to continue to emit the full TeleporterMessage on the sending side (perhaps along with the hash). Since the sender pays for gas anyway, they have a small incentive to make their TeleporterMessage payload less verbose. Then we emit the hash on the receiving side.

**Comment by michaelkaplan13** [comment]
Lets keep the full message in the event to allow for consumers to be able to decode that event data. This issue was also not referenced in the audits either, as the gas savings aren't too significant.

**Comment by michaelkaplan13** [comment]
If necessary, the relayer can also account for the message length and corresponding gas cost when deciding if it wants to relay a message or not. Message senders are also charged gas per byte, prohibiting arbitrarily long messages.
