### ISSUE TITLE
README for pausing Teleporter messages

### ISSUE THREAD

**Issue by geoff-vball** [ava-labs/teleporter#406]
**Context and scope**
We should have a clear README dedicated explaining exactly how to pause all Teleporter messages from being sent and received by an application contract that inherits from `TeleporterUpgradeable`.

This should include template `cast` commands.

**Discussion and alternatives**
`TeleporterUpgradeable` has a public function `pauseTeleporterAddress(address)` that should be called to pause Teleporter messages from that version of Teleporter. The instructions should include steps to ensure that the address is properly paused, and if possible, check which addresses are currently unpaused.

**Comment by michaelkaplan13** [comment]
I would suggest including commands to get all of the Teleporter version addresses supported by the registry used by the given contract, so that it can ensure that all of them are paused.
