### ISSUE TITLE
Staking Manager End-to-end tests

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/teleporter#433]
**Context and scope**
Implement initial end-to-end tests exercising the staking manager contracts. In order to mark this issue as complete, the end-to-end tests should fully exercise the subnet staking contract side of the validator set management flows. Further work on the Avalanchego ACP 77 implementation is required before the end-to-end tests are able to manage the validator sets on the P-Chain.

**Discussion and alternatives**
We should cover at minimum the following cases:
- Adding a validator via `initializeValidatorRegistration`
- Removing a validator via `initializeEndValidation`
- Removing a validator via `ExitValidatorTx`

**Comment by geoff-vball** [comment]
Completed by https://github.com/ava-labs/teleporter/pull/492
