### ISSUE TITLE
Consider parameterizing staking dynamics

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/teleporter#439]
**Context and scope**
We should consider parameterizing min/max staking duration, min/max staking amount, and allowed validator churn rate in the Staking Manager contracts.

**Comment by minghinmatthewlam** [comment]
Min staking duration is added in separate issue, max staking duration not needed
Min staking amount included, max staking amount include in this issue
Allowed churn rate is in separate issue
Min delegation should be included, max delegation is proportional to validator stake amount (up to x amount of validator stake amount).
