### ISSUE TITLE
Consider removing openzeppelin-contracts dependency

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/teleporter#448]
**Context and scope**
With https://github.com/ava-labs/teleporter/pull/397, we added support for upgradeable variants of Teleporter utilities to allow for Teleporter apps to be implemented in an upgradeable fashion. In doing so, we added an additional submodule dependency for `openzeppelin-contracts-upgradeable` in addition to the existing `openzeppelin-contracts` submodule.

`openzeppelin-contracts-upgradeable` itself includes `openzeppelin-contracts` as a submodule, so our `openzeppelin-contracts` submodule is likely redundant.

**Discussion and alternatives**
This may help reduce the chance of import conflicts, which can cause headaches in CI. 

**Open questions**
We currently don't enforce similar versions for `openzeppelin-contracts` and `openzeppelin-contracts-upgradeable`. Are we comfortable using the `openzeppelin-contracts` version specified in `openzeppelin-contracts-upgradeable`?

**Comment by geoff-vball** [comment]
Completed
