### ISSUE TITLE
Extensions for Proof-of-Authority support

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/teleporter#449]
**Context and scope**
Subnet validators are registered on the P-Chain in the same way for proof of authority subnets as for proof of stake subnets. A variant of the Staking Manager contract could support PoA validator registration by requiring all validator management operations be conducted by or signed by an admin address. No tokens would need to be locked; instead the admin sets the weight arbitrarily.

**Design**
The PoA variant will be implemented as an upgradeable contract that inherits from `StakingManager`. Migrating to PoS would involve upgrading to a different contract that also inherits from `StakingManager`; in doing so, the contract state pertaining to the registered validators can be migrated cleanly.

**Open questions**
We will need to exclude migrated PoA validators from being able to claim staking rewards. There are many ways to do so, here are a few options:
- On migration, set the PoA validator weights to 0 in the staking contract. This does not affect the weights registered on the P-Chain and used for consensus
- When PoA validator registration is complete, set it's weight to zero. This saves us from having to do so as part of migration
- Mark the block timestamp at which migration occured, and exclude any validators that began before that time from claiming staking rewards.

**Comment by geoff-vball** [comment]
Could the PoA address just be set as the `Subnet Validator Manager`? It could send warp messages directly to change the validator weights. You'd just lose tracking of any pending validator set changes on the subnet, but I don't imagine PoA subnets are changing this very frequently.

**Comment by cam-schultz** [comment]
We should consider implementing this as the base contract, and extending with staking rewards management, rather than the other way around. PoA staking management consists solely of tracking the validator set.

**Comment by cam-schultz** [comment]
Marked as "Deprioritized" pending ongoing PoA design discussions.
