### ISSUE TITLE
Unlock stake and issue rewards

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/teleporter#489]
a**Context and scope**
After completing a validation and calculating the staking rewards (#436), we should unlock those rewards such that they can be redeemed by the staker.

- [x] https://github.com/ava-labs/teleporter/pull/527
- [x] https://github.com/ava-labs/teleporter/pull/539
- [x] https://github.com/ava-labs/teleporter/pull/534
- [ ] look at removing the stale validationPeriods state if no longer needed

**Comment by minghinmatthewlam** [comment]
after unlocking the staking rewards as part of `completeEndValidation` should also look at removing the stale `validationPeriods` state if no longer needed
