### ISSUE TITLE
Remove Ed25519 Signature from initializeValidatorRegistration

### ISSUE THREAD

**Issue by michaelkaplan13** [ava-labs/teleporter#493]
**Context and scope**
The ACP-77 spec has been updated to no longer require an Ed25519 signature to register a node ID as a validator.

**Discussion and alternatives**
See updated spec [here](https://github.com/avalanche-foundation/ACPs/tree/main/ACPs/77-reinventing-subnets). The `initializeValidatorRegistration` parameters should match those required for the message in `RegisterSubnetValidatorTx`s specified [here](https://github.com/avalanche-foundation/ACPs/tree/main/ACPs/77-reinventing-subnets#registersubnetvalidatortx).

The message structs sent to the P-Chain should also be updated to reflect the latest version of the spec.

**Comment by geoff-vball** [comment]
Completed by https://github.com/ava-labs/teleporter/pull/492
