### ISSUE TITLE
Compounding rewards calculator

### ISSUE THREAD

**Issue by geoff-vball** [ava-labs/teleporter#494]
**Context and scope**
We should create a compounding rewards calculator so that validators are not incentivized to end their staking period and restake frequently.

**Discussion and alternatives**
Solidity only natively supports integer math. We may need a library for this, or would could probably get by with a reasonable approximation (ex: compound every X days).

**Open questions**
Can/should we allow the validator to update their stake weight on the p-chain based on their current compounded rewards?

**Comment by cam-schultz** [comment]
Closing in favor of https://github.com/ava-labs/teleporter/issues/526. They both would have similar effects when claiming validation rewards on ending a validation, but 526 also unlocks much better UI that doesn't require evicting delegators before claiming rewards.
