### ISSUE TITLE
Delegation: Basic rewards calculation

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/teleporter#506]
**Context and scope**
The delegation rewards should follow the same rewards curve as validator staking rewards. We should extend the rewards manager interface to support delegators as well.

**Discussion and alternatives**
- The actual calculation that's implemented should be as simple as possible. The rewards manager interface may take arbitrarily complex implementations, but those are outside the scope of this repo.
- The calculation should prorate rewards based on delegator entry and exit times.
- The calculation should take into account the _total_ validator rewards based on uptime, but should not take into account the uptime during the delegation period. It's possible to claim rewards for a delegation period during which the validator was never online, but it's worth noting that this is already true under the existing (pre ACP-77) delegation rules. In any case, to do so would require a much more complex uptime proof than is planned to be implemented by VMs.
- Rewards should not be eligible to be claimed until after the delegation period has ended.

**Comment by geoff-vball** [comment]
Closing this: delegation rewards will be calculated exactly the same as validator rewards.
