### ISSUE TITLE
Disallow existing PoA validators from staking rewards

### ISSUE THREAD

**Issue by minghinmatthewlam** [ava-labs/teleporter#519]
**Context and scope**
Follow up from #508 , if there are existing PoA validators they will exit the validator set by calling `initializeEndValidation`. After the migration to PoS, this call would take in an uptime proof which PoA validators also have. We need to make sure PoA validators can't claim rewards because they didn't have an initial stake amount locked up.

**Discussion and alternatives**
Options thought of:
1. PoS validator manager contract at initialization saves the timestamp to mark as reward start time, only validations with a start time > reward start time are eligible for rewards
2. Everytime PoS adds a validator it keeps track of which validation ID it added, and only allows rewards for validations added through PoS
3. In the saved validator info we can save whether each validator is reward eligible, and PoA validators would all be added as ineligibile.

**Comment by iansuvak** [comment]
Option 1 above seems like the least net new state and cleanest. Any opposition to just going with that?

**Comment by iansuvak** [comment]
We should address this in #547 since that already adds `_isPosValidator` helper

**Comment by geoff-vball** [comment]
This is addressed in https://github.com/ava-labs/teleporter/pull/534
