### ISSUE TITLE
validate initial validator set from ConvertSubnetTx

### ISSUE THREAD

**Issue by minghinmatthewlam** [ava-labs/teleporter#542]
**Context and scope**
Update to ACP77, will have `ConvertSubnetTx` specify an initial set of PAYG validators, that can only be removed from the validator manager. The idea is for validator manager contract to accept an initial validator set that was specified in `ConvertSubnetTx`, and the contract would not be able to initialize other validators until this process is done.

**Discussion and alternatives**
For verification, there might be a new P-Chain message type that includes all these new validators. The validator manager contract should get this verified Warp message, verify the message, and parse for the initial validator set. Then the contract needs to compute new validation IDs to associate these validators, which can look like `sha256(convertSubnetTxID,validatorIndex)`. 

**Open questions**
Will there be a separate function to initialize this validator set, or can it be done through contract construction in the `initialize` functions? The caveat being migration from PoA->PoS, we need to make sure that the `reinitializer` of the PoS contracts can not specify another initial validator set that was already specified as part of PoA contract initially.

**Comment by meaghanfitzgerald** [comment]
will `initializeValidatorSet`  in https://github.com/ava-labs/teleporter/pull/547 need to be called manually by the creator of the L1 or will the initial validator set be added to the set tracked by the ValidatorManager via the contructor?

**Comment by minghinmatthewlam** [comment]
> will `initializeValidatorSet` in #547 need to be called manually by the creator of the L1 or will the initial validator set be added to the set tracked by the ValidatorManager via the contructor?

will ned to be called separately. At genesis we can still pass the parameters required for `initialize`, but at genesis we do not have the subnet conversion tx ID, which is found after `ConvertSubnetTx`.

**Comment by cam-schultz** [comment]
Completed by https://github.com/ava-labs/teleporter/pull/547
