### ISSUE TITLE
initial validator set ending and rewards

### ISSUE THREAD

**Issue by minghinmatthewlam** [ava-labs/teleporter#543]
**Context and scope**
Relates to #542 , we need special handling for the initial validator set, in terms of who can initialize and complete validation for these validators, and making sure no rewards can be given to them.

**Discussion and alternatives**
For PoA, the owner should be able to initialize end validation for the validator set, and likely anyone can complete end validation similar to other validators.

For PoS, there's no original sender that initialized validator registration, so should anyone be able to initialize end validation here? Does it make sense to have a minimum time before these validators can be ended?

**Comment by cam-schultz** [comment]
Completed by https://github.com/ava-labs/teleporter/pull/547
