### ISSUE TITLE
Optimize gas usage when writing ValidatorManager objects

### ISSUE THREAD

**Issue by geoff-vball** [ava-labs/teleporter#613]
**Context and scope**
In the `validator-manager` contracts, there are multiple functions where we update more than one, but not all of the fields of an object. We should investigate in each case whether one write of the whole object, or multiple writes of its fields are more gas efficient.

**Comment by Ronnieraj37** [comment]
Hi @geoff-vball ,

I just tested updating objects for a Struct one by one is more gas effecient. I applied this to 

```
$._posValidatorInfo[validationID] = PoSValidatorInfo({
        owner: _msgSender(),
        delegationFeeBips: delegationFeeBips,
        minStakeDuration: minStakeDuration,
        uptimeSeconds: 0
 });
 ```
 Changing it to : 
 ```
        $._posValidatorInfo[validationID].owner= _msgSender();
        $._posValidatorInfo[validationID].delegationFeeBips= delegationFeeBips;
        $._posValidatorInfo[validationID].minStakeDuration= minStakeDuration;
        $._posValidatorInfo[validationID].uptimeSeconds= 0;
```
And these were the results :

| Test Function                                | Gas Before | Gas After |
|----------------------------------------------|------------|-----------|
| testCompleteDelegatorRegistration            | 502615     | 502428    |
| testCompleteDelegatorRegistrationImplicitNonce| 582923    | 582736    |
| testCompleteDelegatorRegistrationValidatorCompleted| 644546| 644360    |
| testCompleteDelegatorRegistrationWrongNonce  | 581666     | 581480    |
| testCompleteEndDelegation                    | 649322     | 649136    |

This works in this case but there might be cases where updating all values at once might be more optimal as this method calls sstore multiple times.

Can I work on this issue @geoff-vball ?

**Comment by cam-schultz** [comment]
Hey @Ronnieraj37 thanks for conducting that experiment. Feel free to open PRs with these gas optimizations. As you already pointed out, this particular patten may only yield gas savings in certain cases, but it would be good to also document the cases that don't in the form of a comment so that we know what's been examined.

I'll go ahead and assign this ticket to you.

**Comment by Ronnieraj37** [comment]
Sure @cam-schultz will create a PR by this weekend.
