### ISSUE TITLE
Consider TeleporterRegistry deployment through Nick's method

### ISSUE THREAD

**Issue by minghinmatthewlam** [ava-labs/teleporter#76]
**Context and scope**
`TeleporterRegistry` is currently implemented without Nick's method, so will end up at different addresses across different subnet chains. The registry needs Warp out-of-band messages to update, and do so validators need to add the Warp out-of-band message bytes, and we want to streamline this process as much as possible.

**Discussion and alternatives**
We would need to remove the calls in the registry' constructor, which include registry initialization and getting warp blockchain ID, out of constructor, to prevent the deployment from failing and using up the nonce. 

**Open questions**
The destination chain ID between Warp messages would be different already anyways, how can we streamline this too?

**Comment by michaelkaplan13** [comment]
Closing this issue since the `deploy_registry.sh` script handles the deployment of the registry, which doesn't need to be at the same address on every chain.
