### ISSUE TITLE
Consider hosting "stable" foundry releases to avoid purging

### ISSUE THREAD

**Issue by michaelkaplan13** [ava-labs/teleporter#88]
**Context and scope**
We currently install a specific nightly [foundry release](https://github.com/foundry-rs/foundry/releases/tag/nightly-70d00222c2ef74fc484b8d98c5705d131ab31871) in our integration test flow. Foundry may prune this version in the future such that it's no longer available as a pre-built release.

**Discussion and alternatives**
Consider either:
1. Building from source
2. Hosting the specific foundry release we'd like to install in an image repository like Dockerhub to ensure that it can't be removed from underneath unexpectedly.

**Comment by geoff-vball** [comment]
I would suggest fairly strongly against building from source. It requires us to first install `cargo`, which takes a very long time, and also building foundry also take a very long time. Of course these steps should be cached after being completed once, but we're talking an extra almost 30 minutes of build time when required.

**Comment by minghinmatthewlam** [comment]
closed with https://github.com/ava-labs/teleporter/pull/101
